module.exports = {
    RECEIVE_USER: 'RECEIVE_USER',
    LOGIN_FAIL: 'LOGIN_FAIL',
    ADD_TOKEN: 'ADD_TOKEN',
    REMOVE_TOKEN: 'REMOVE_TOKEN',
    LOOKATION_TOKEN: 'lookation-token',
    DISCONNECTED: 'DISCONNECTED',
    RECEIVE_CURRENT_LOCATION: 'RECEIVE_CURRENT_LOCATION',
    ACTION: 'ACTION',
    RECEIVE_WATCHID: 'RECEIVE_WATCHID',
    CREDENTIALS: 'CREDENTIALS',
    POPUP: 'POPUP',
    RECEIVE_LOOKERS_POSITIONS: 'RECEIVE_LOOKERS_POSITIONS'
}
